name: CI

on:
  push:
    branches:
      - main
      - master
  pull_request:

jobs:
  yunohost-integration:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: YunoHost/ci_action@v1
        with:
          # The ID of the app in the manifest
          app_id: taiga
          # Custom tests.toml file
          custom_tests: tests.toml
